info:
  app:
    name: @project.artifactId@
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
server:
  port: 8002
logging:
  level:
    com.itmuch.study.microserviceconsumermovie.service.UserFeignClient: debug
