info:
  app:
    name: microservice-simple-provider-user
    encoding: UTF-8
    java:
      source: 1.8.0_161
      target: 1.8.0_161

server:
  port: 8000
  
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
